#!/bin/bash

# Necesita su plantilla LaTeX específica, que está en ../utils y que tendrás
# que copiar a su directorio de plantillas de Pandoc.

ficheros=""
for fichero in $( ls ??.*.md)
do
    ficheros="$ficheros $fichero" 
done

echo $ficheros

pandoc --template=/home/jmerelo/Libros/cero_a_perl/utils/cero_a_perl.latex \
    -V language=spanish -V mainlang=spanish -V lang=spanish  \
    -V author='JJ Merelo' -V title='De cero a Perl'\
    -V documentclass=book\
    -S --latex-engine=xelatex  \
    -o cero_a_perl.pdf  \
    $ficheros  --toc



