#!/bin/bash

# Tendrás que cambiar el camino a la plantilla, que tiene que ser absoluto

ficheros=""
for fichero in $( ls ??.*.md)
do
    ficheros="$ficheros $fichero" 
done

echo $ficheros

pandoc --template=/home/jmerelo/Libros/cero_a_perl/utils/cero_a_perl.latex \
    -V language=spanish -V mainlang=spanish -V lang=spanish  \
    -V author='JJ Merelo' -V title='De cero a Perl'\
    -V documentclass=book\
    -S --latex-engine=xelatex  \
    -o cero_a_perl.pdf  \
    $ficheros  --toc



